/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dict.h"

bool_t
xdr_dict_in (XDR *xdrs, dict_in *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->word, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mean, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dict_out (XDR *xdrs, dict_out *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->word, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (dict_out), (xdrproc_t) xdr_dict_out))
		 return FALSE;
	return TRUE;
}
