/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DICT_H_RPCGEN
#define _DICT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dict_in {
	char word[100];
	char mean[100];
};
typedef struct dict_in dict_in;

struct dict_out {
	char word[100];
	struct dict_out *next;
};
typedef struct dict_out dict_out;

#define DICT_PROG 0x13451111
#define DICT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define init 1
extern  void * init_1(dict_in *, CLIENT *);
extern  void * init_1_svc(dict_in *, struct svc_req *);
#define insert 2
extern  void * insert_1(dict_in *, CLIENT *);
extern  void * insert_1_svc(dict_in *, struct svc_req *);
#define search 3
extern  dict_out * search_1(dict_in *, CLIENT *);
extern  dict_out * search_1_svc(dict_in *, struct svc_req *);
#define delete 4
extern  int * delete_1(dict_in *, CLIENT *);
extern  int * delete_1_svc(dict_in *, struct svc_req *);
extern int dict_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init 1
extern  void * init_1();
extern  void * init_1_svc();
#define insert 2
extern  void * insert_1();
extern  void * insert_1_svc();
#define search 3
extern  dict_out * search_1();
extern  dict_out * search_1_svc();
#define delete 4
extern  int * delete_1();
extern  int * delete_1_svc();
extern int dict_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dict_in (XDR *, dict_in*);
extern  bool_t xdr_dict_out (XDR *, dict_out*);

#else /* K&R C */
extern bool_t xdr_dict_in ();
extern bool_t xdr_dict_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DICT_H_RPCGEN */
